### ISSUE TITLE
Utilize this original repo via organization instead of forking

### ISSUE THREAD

**Issue by westonganger** [axlsx-styler-gem/axlsx_styler#23]
As someone who uses this project heavily in SpreadsheetArchitect, I have a few concerns about the forking of this project:

- Forking make all the github stars go back to zero
- Forking makes the project un-searchable
- Forking kills all SEO

In essence, Forking is not the right answer for hand-off of development of a project/plugin.

Could we instead utilize this original repo by creating an organization? Ex. axlsx-styler-gem/axlsx_styler. This would enable future maintainers to completely the repo without any interaction from the original author and it would solve all of these issues.

**Comment by westonganger** [comment]
Can we implement the above recommendations? I would be happy to be a maintainer for this. I have a good track record of supporting my own and other's open source work as you will see by exploring my profile/repos. I am also vested in keeping your name, the original author, attached as you have put in a ton of work to this project and I believe it would be a shame to not be recognized for that.

**Comment by sakovias** [comment]
@westonganger thank you for some great ideas and for stepping up! It would be great to have this tool maintained and moved forward by one or more motivated people from the Ruby community.

If @davefp's fork didn't move too far I'd be happy to have this repo moved under a separate org as you propose. What needs to be done on my side to make this happen? I can help out over the Canada day long weekend.

**Comment by westonganger** [comment]
Yes so create a Github organization and add me with Admin permissions.

**Comment by westonganger** [comment]
For naming the organization I have previously been annoyed  by the naming. For example this project I maintain: 

https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview

Sometimes I wish we had tried to have the original authors name included in the organization name. So maybe for this organization I recommend naming it `sakovias-org` or something you think makes better sense.

**Comment by sakovias** [comment]
@westonganger I've moved this repo to a new org and invited you and @davefp to contribute (we've previously had a discussion with @davefp about a transfer of ownership). I'd like to step outside of this project and let you guys maintain it and make decisions. I guess some work still needs to be done to let you publish future releases on RubyGems.

**Comment by westonganger** [comment]
```
gem owner axlsx_styler --add westonganger@gmail.com
```

**Comment by sakovias** [comment]
Done with the ownership for @westonganger.

Just noticed a potential RubyGems issue in line with @westonganger's warning:

- RubyGems displays stars for the fork (currently 4 vs 44 on `axlsx-styler-gem/axlsx_styler`)
- All but Homepage links on RubyGems point to @davefp's fork - `davefp/axlsx_styler`

**Comment by westonganger** [comment]
Cool well I think like we can close this issue then.

I've added my first commit by cleaning up the readme significantly and extracted the changelog to a seperate file.

**Comment by westonganger** [comment]
@davefp you can add your name to the README, I just havent heard a peep from you so wondering if you will be joining up.

**Comment by davefp** [comment]
Hi folks,

I've been away from GitHub over the last few days so I'm just catching up now.

I see you've created a new org and pointed the rubygems page to it. Have you merged the commits I had on my fork into the main repo? If not you should.

@westonganger I've accepted the org invite but from the sounds of things you make way more use of the gem than I do (my usage is largely styling a single weekly report we generate for clients).

Based on that I'm happy to sit back and be a reactive (triaging issues, fixing bugs) rather than proactive (introducing new features, adding support for new ruby features) maintainer. Does that reasonable?

**Comment by westonganger** [comment]
Sounds good @davefp, glad to hear from you. Thats mainly my intention too however I am willing to get dirty if theres a reason.

This has been very stable software and I don't think theres any need to mess with that at this time. Until someone raises an issue with a use case for any new features/changes we will leave it. 

I would like to release v1.0.0 at some point to signify this is stable software, however it would probably be nice to if `axlsx` fully releases v3.0.0 first.

**Comment by sakovias** [comment]
Thanks again guys for taking it over.

I believe some improvements can be made in the area of end-to-end tests before a v1 release:

- The integration tests as of this writing are more like unit tests. Excel files have to be manually verified before a release. Image comparison or XML-parsing tools may help with this.
- Integration tests with Rails or other frameworks would be great to have. I personally broke a couple of releases due to lack of integration tests.

**Comment by westonganger** [comment]
Perfect glad to hear your suggestions. I will add Rails integration to the test suite. I'll create an issue for the other suggestion.
